"""empty message

Revision ID: 18e37632f9f5
Revises: 38c166803e4e
Create Date: 2024-02-16 21:53:23.203111

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18e37632f9f5"
down_revision = "38c166803e4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_set_id", sa.Integer(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.Column("alg", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_set_id"],
            ["key_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "registration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column(
            "platform_login_auth_endpoint", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "platform_service_auth_endpoint", sa.String(length=255), nullable=False
        ),
        sa.Column("platform_jwks_endpoint", sa.String(length=255), nullable=False),
        sa.Column("key_set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_set_id"],
            ["key_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "client_id"),
    )
    op.create_table(
        "deployment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.String(length=255), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deployment")
    op.drop_table("registration")
    op.drop_table("key")
    op.drop_table("key_set")
    # ### end Alembic commands ###
