"""empty message

Revision ID: 38c166803e4e
Revises: 
Create Date: 2024-02-16 21:52:47.294151

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38c166803e4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("refresh_key", sa.String(length=255), nullable=True),
        sa.Column("expires_in", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
